### ISSUE TITLE
Could not refresh access token. You probably need to re-authorise yourself...

### ISSUE THREAD

**Issue by steverethink** [benchmarkstudios/slackbox#14]
Then full error when using the slash command in slack is as follows:

"Could not refresh access token. You probably need to re-authorise yourself from your app's homepage."

Overall slackbox seems to be working fine, but we're constantly needing to re-authorise the app in order to get it to work again. Its almost like we're having to visit the apps homepage to authorize at least every hour or else it stops working.

We made sure that the callback and redirect URI's are correct. Anyone know what could be up with this?

**Comment by brianroach** [comment]
I too am experiencing this issue.

**Comment by jtothebell** [comment]
I ran into this issue as well. My first suspicion is that its running on a free heroku instance that turns off when there are no requests for a certain amount of time, but that is a wild guess.

**Comment by mwickett** [comment]
Yes, every time the server goes to sleep, it requires you to refresh the access token.
