### ISSUE TITLE
Which fork?

### ISSUE THREAD

**Issue by visch** [benchmarkstudios/slackbox#17]
Which fork does everyone like best? 

https://github.com/thorgate/slackbox looks to be the good as well as many others, any other recommendations as there's a good number of forks atm.

**Comment by mikefrancis** [comment]
@visch Is this really an issue?

Just trying to see where you are going with this?

**Comment by visch** [comment]
It's not an issue with this repo no. It'd be nice to know which fork is active, but yeah this can be closed.
