### ISSUE TITLE
Playlist Not Found

### ISSUE THREAD

**Issue by markrjamieson** [benchmarkstudios/slackbox#18]
I've followed the instructions, App is installed and seems to be working fine, but the app can't seem to find the playlist. In slack I get the following message: Playlist doesn't exist

Has Spotify changed how they do Playlist IDs so that this integration doesn't correctly work at the moment? I tried using the full URL of the playlist after this and I still got an error: Request failed

**Comment by mikefrancis** [comment]
Is the playlist set to public? Also as it's been a few hours, have you tried again? Had problems in the past where the playlist doesn't show up straight away, probably due to caching.

**Comment by markrjamieson** [comment]
Hey Mike,

Worked out that it was because I needed to have the User variable set to my user ID number rather than my username! Now it’s working!

Cool little integration, we’re going to connect it up with a SONOS in our office to play some tunes.

Been looking at something a little more complex next but not sure if it will work on Heroku as is - https://github.com/smashingboxes/maestro
Have you seen this one?

Regards,

Mark Jamieson
Operations Engineer | Platform Engineering
550 Bourke Street, Melbourne, Victoria, 3000, Australia
M: +61 424 681 368 | D: +61 (03) 9671 7815
majamieson@deloitte.com.au<mailto:majamieson@deloitte.com.au> | www.deloitte.com<http://www.deloitte.com/>

[cid:image001.png@01D23CDB.5E5C7E30]<http://www2.deloitte.com/au/en.html?utm_source=outlook&utm_medium=email&utm_campaign=exc-outlook-signature&utm_content=logo>
--
Please consider the environment before printing.

**Comment by mikefrancis** [comment]
@markrjamieson I hadn't seen Maestro, no - looks good though, thanks for sharing.

To be honest, Slackbox was just a tech demo, we weren't looking to build anything remotely enterprising so it's good to see others running with the idea and if you check out the forks of the project some people have really made it their own.

Will close this issue for now, but thanks again and glad you got it sorted 😄
