### ISSUE TITLE
Add as next song

### ISSUE THREAD

**Issue by guidodipaolo** [benchmarkstudios/slackbox#19]
Hi !! 

There is any possibility to add a song as the next one on the playlist and not as the last ?

Thanks !!

**Comment by mikefrancis** [comment]
Looking at the [docs](https://developer.spotify.com/web-api/add-tracks-to-playlist) I am not sure this is possible - you can specify a `position` which is an number denoting where you want to add it in the queue.

Problem is you would need to know your own current position within that playlist, increment that number and add this as the position - I am not sure how you would go about doing this.

Feel free to submit a pull request though.
