### ISSUE TITLE
What Spotify account do you need?

### ISSUE THREAD

**Issue by mvaneijgen** [benchmarkstudios/slackbox#2]
I have the $5 free ad version and I keep getting
`Could not referesh access token, you probably need to auth yourself again.`

**Comment by mikefrancis** [comment]
@mvaneijgen Just to confirm, have you followed the install instructions and "authed" yourself initially on your app's homepage?

**Comment by mvaneijgen** [comment]
@mikefrancis yes

**Comment by mikefrancis** [comment]
@mvaneijgen Ok. This has only been tested with a premium account and I can't find anything in Spotify's docs to suggest that this endpoint is only open to Premium users.

Will give it a try with a free account.

**Comment by mvaneijgen** [comment]
Sorry it was me and btw testeed with free account and it works! (the call back URI weren't the same one was http:// and the other https://)

**Comment by mikefrancis** [comment]
Ah, ok :smile: 

@bmsdan or @pdcreis can you please mark this issue as closed, cheers.

**Comment by mvaneijgen** [comment]
@mikefrancis I didn't want to start a new issue, but over night I needed to re-auth is this normal?

**Comment by mikefrancis** [comment]
@mvaneijgen Yes it is, the tokens only last for a limited amount of time.

**Comment by tduarte** [comment]
I'm having the same issue, I need to relogin a lot of times in a day. How can we change that expiration time? Or maybe do something to automatic authenticate again.

**Comment by bmsdan** [comment]
Closing this issue in favour of this more recent question over access token expiry so we can keep everything in one place:

https://github.com/benchmarkstudios/slackbox/issues/5
