### ISSUE TITLE
24 hour auth

### ISSUE THREAD

**Issue by seanecoffey** [benchmarkstudios/slackbox#22]
Hey, similar to a couple of the issues that have been opened before, the ticket is expiring every 24 hours and a new one isn't being automatically grabbed (is it meant to, I'm not sure the spotify API page makes this clear to me). 
I'm running on a hobby dyno that doesn't sleep so It's not a heroku issue, any ideas?

**Comment by bmsdan** [comment]
Each time a /jukebox request is made the Spotify access and refresh tokens are updated. It's possible that if a request isn't made within that 24 hour period then the previously set tokens would expire. Could this explain the issue in this case?

**Comment by seanecoffey** [comment]
I think it explains the issue yes. is there a way to reset the token without making a jukebox request?
