### ISSUE TITLE
The access token expired

### ISSUE THREAD

**Issue by vDeo** [benchmarkstudios/slackbox#5]
If there is an influx of activity, the following error message shows: 
"The access token expired"
Maybe there's a problem with requesting a refresh token?

**Comment by matiassingers** [comment]
A simple approach would be to use `setInterval()` or something similar and then refresh the token before expiration.

**Comment by vDeo** [comment]
@matiassingers I don't think that would solve the problem. The issue is that the app is not setting the refreshed access token sometimes, which breaks the app. https://developer.spotify.com/web-api/authorization-guide/ take a look at the diagram there.

To fix the issue I have to manually go into my Spotify App and reset the client secret and set it on the heroku app.

**Comment by bmsdan** [comment]
A new access token is returned by the `setAccessToken()` method but wasn't being set. The latest version of Slackbox now stores this access token and, over a 24 hour period of testing, appears to resolve this issue. Let us know how you get on.

**Comment by vDeo** [comment]
@bmsdan After a day of testing at our office, it seems to working as expected. Thanks!
