### ISSUE TITLE
When searching for a song that has the same title as its album, the first song on the album gets selected instead.

### ISSUE THREAD

**Issue by taylorsolomon** [benchmarkstudios/slackbox#6]
`/jukebox Michael Jackson - Off the Wall` results in "Don't Stop Till You Get Enough" being added, presumably since it's the first song in the album.

This could be solved using a slightly more elaborate syntax like `[Artist] - [Album] - [Song]`.

**Comment by bmsdan** [comment]
Great idea. We've allowed for an `[Artist] - [Track]` syntax now which returns much more accurate results.

Searches on track name alone are still supported and should also provide better matches: e.g. `/jukebox Off the Wall`
