### ISSUE TITLE
"You cannot add to a playlist you don't own"

### ISSUE THREAD

**Issue by brettsinn** [benchmarkstudios/slackbox#8]
Was working just fine on a collaborative playlist, but as of this morning my colleagues are getting "You cannot add to a playlist you don't own."

**Comment by mikefrancis** [comment]
Is this a public or private playlist?

**Comment by brettsinn** [comment]
Public - https://open.spotify.com/user/brettsinn/playlist/3D1D3CI0wzuLPYfh1ddvwN

**Comment by mikefrancis** [comment]
Have they tried reauthorising themselves?

**Comment by mikefrancis** [comment]
@brettsinn Going to guess you got this resolved? If so please can you let us know so we can close this issue.
