### ISSUE TITLE
"Could not find that track" and "Playlist doesn't exist"

### ISSUE THREAD

**Issue by niqueeta** [benchmarkstudios/slackbox#9]
Everything is set up properly, but I keep getting either "Could not find that track" (for songs  and artists name copied directly from Spotify) or "Playlist doesn't exist" (playlist definitely exists).

Any idea where I should be looking?

**Comment by niqueeta** [comment]
"Could not find that track" - problem identified. Command seems to use em dash (—), I was using normal dash (-). "Playlist doesn't exist" still happening, though.

**Comment by chelpixie** [comment]
Same. Only getting the "playlist doesn't exist error. Could use some clarification.

**Comment by bmsdan** [comment]
Check that your `SPOTIFY_PLAYLIST_ID` variable is set, valid and corresponds to a playlist that is owned by the authenticated Spotify user. On the example below, the ID would be the last portion of the URL - `48910w3L1DNiqvMHbUfZyY`:

`https://play.spotify.com/user/spotify_uk_/playlist/48910w3L1DNiqvMHbUfZyY`

**Comment by niqueeta** [comment]
![screen shot 2015-07-09 at 13 36 32](https://cloud.githubusercontent.com/assets/5340342/8595150/b529fc46-263f-11e5-951a-8f9f009db8da.png)
![screen shot 2015-07-09 at 13 36 55](https://cloud.githubusercontent.com/assets/5340342/8595151/b52a027c-263f-11e5-98f4-7f4f068f9d45.png)

Yes, I have checked that. Screenshot for evidence. Have tried creating other playlists as well, and generating new client IDs. Still nothing. Could it be something else?

**Comment by chelpixie** [comment]
That worked for me! Thank you!

**Comment by mikefrancis** [comment]
@niqueeta Rather than posting a screenshot could you post a link to your playlist?

**Comment by niqueeta** [comment]
https://open.spotify.com/user/114536057/playlist/40Mg3lTwASuHJ5kriPgi5E

(it's a different one now, but I have updated the heroku settings)

**Comment by mikefrancis** [comment]
And since updating this you have gone back through the installation process?

**Comment by niqueeta** [comment]
Yes, I've started from scratch, created a new Spotify app, etc. Still getting "this playlist doesn't exist"

**Comment by mikefrancis** [comment]
I think it's something to do with your username - what are you using for `SPOTIFY_USERNAME` at the moment. You don't seem to have one, just a number. Go into your Spotify account settings and see if you can give yourself a username or contact their support, then try again.

**Comment by niqueeta** [comment]
Ok, yes, that was it. I changed the username to that number and it worked fine. I was using my facebook username. I did think that it might not work out the same, but since the authorisation worked I assumed it was fine. Anyway, thank you!

**Comment by mikefrancis** [comment]
@niqueeta No problem - for anyone arriving from Google, your Facebook username isn't always the same as your Spotify username (at least mine isn't the same) so that's why it asks for the Spotify username, otherwise it won't be able to find a playlist for that user.
